knp_menu:
  # use "twig: false" to disable the Twig extension and the TwigRenderer
  twig:
    #template: knp_menu_custom.html.twig
    template: Menu/knp_menu_b5.html.twig
  #  if true, enables the helper for PHP templates
  templating: false
  # the renderer to use, list is also available by default
  default_renderer: twig